# Generated by Django 2.1.7 on 2019-03-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('middle_name', models.CharField(max_length=75)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BoxSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('middle_name', models.CharField(max_length=75)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('television', models.BooleanField(default=False)),
                ('medium', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('for_rent', models.BooleanField(default=False)),
                ('on_loan', models.BooleanField(default=False)),
                ('actors', models.ManyToManyField(blank=True, to='vhs_library.Actor')),
                ('box_set', models.ManyToManyField(blank=True, to='vhs_library.BoxSet')),
                ('directors', models.ManyToManyField(blank=True, db_index=True, to='vhs_library.Director')),
                ('distributors', models.ManyToManyField(blank=True, to='vhs_library.Distributor')),
                ('genres', models.ManyToManyField(max_length=75, to='vhs_library.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vhs_library.Network'),
        ),
        migrations.AddField(
            model_name='movie',
            name='studios',
            field=models.ManyToManyField(blank=True, to='vhs_library.Studio'),
        ),
    ]
